name: "Hello World workflow"

# Control when the action will run. Triggers the Workflow on push done to master or production barnch
on:
    push:
        branchches:
            - master
            -  production

jobs:
    hello_world:
        runs-on: ubuntu-latest
        steps:
            - name: "Print Hello World"
            run: echo "Hello World"
            - name: "Print Current Date"
            run: date